import type { Healthcare } from "@/types/healthcare";


export const providers: Healthcare[] = [
    {
      id: "1",
      name: "Doren Hospital",
      address: "123 Main St, Anytown, USA",
      contact_number: "123-456-7890",
      email: "info@dorenhospital.com",
      website: "https://dorenhospital.com",
      owner_name: "John Doe",
      license_number: "123456",
      tax_id_number: "123456789",
      country: "USA",
      city: "Anytown",
      state: "CA",
      longitude: "-122.4194",
      latitude: "37.7749",
      zipcode: "94107",
      healthcare_type: "hospital",
      healthcare_services: ["emergency", "diagnosis", "therapy"],
      created_at: "2022-01-01",
      updated_at: "2022-01-01",
    },
    {
      id: "2",
      name: "Maxima Hospital",
      address: "123 Main St, Anytown, USA",
      contact_number: "123-456-7890",
      email: "info@dorenhospital.com",
      website: "https://dorenhospital.com",
      owner_name: "John Doe",
      license_number: "123456",
      tax_id_number: "123456789",
      country: "USA",
      city: "Anytown",
      state: "CA",
      longitude: "-122.4194",
      latitude: "37.7749",
      zipcode: "94107",
      healthcare_type: "hospital",
      healthcare_services: ["emergency", "diagnosis", "therapy"],
      created_at: "2022-01-01",
      updated_at: "2022-01-01",
    },
  ];

 export const insuranceCoverages = [
    "Hospitalization / Inpatient Care",
    "Outpatient / Ambulatory Care",
    "Emergency Care",
    "Surgical Procedures",
    "Prescription Drugs",
    "Maternity & Newborn Care",
    "Mental Health Services",
    "Rehabilitation & Therapy",
    "Preventive & Wellness Services",
    "Chronic Disease Management",
    "Alternative Medicine",
    "Dental - Preventive Care",
    "Dental - Basic Procedures",
    "Dental - Major Procedures",
    "Dental - Orthodontics",
    "Vision - Eye Exams",
    "Vision - Lenses & Frames",
    "Vision - Corrective Procedures",
    "Disability - Short-Term",
    "Disability - Long-Term",
    "Life Insurance - Term Life",
    "Life Insurance - Whole/Universal Life",
    "Accidental Death & Dismemberment (AD&D)",
    "Travel Insurance",
    "Critical Illness Insurance",
    "Long-Term Care Insurance",
    "Worker’s Compensation Insurance",
    "Motor Vehicle Medical Coverage",
  ];